services:
  easy_slides:
    image: mona233/easy_slides:latest
    container_name: easy_slides
    ports:
      - "10001:10001"
    volumes:
      - type: bind
        source: ./media
        target: /app/media
        bind:
          create_host_path: false
      - type: bind
        source: ./db.sqlite3
        target: /app/db.sqlite3
        bind:
          create_host_path: false
    restart: always
    environment:
      - CSRF_TRUSTED_ORIGINS=https://localhost,https://yourdomain.com  # 定义CSRF信任域
