# Generated by Django 6.0.5 on 2026-05-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideapp', '0002_slide_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
