# Generated by Codex on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideapp', '0003_slide_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
