# Generated by Codex on 2026-05-25

from django.db import migrations, models
import django.db.models.deletion


def migrate_legacy_categories(apps, schema_editor):
    Slide = apps.get_model('slideapp', 'Slide')
    SlideCategory = apps.get_model('slideapp', 'SlideCategory')

    category_positions = {}
    for slide in Slide.objects.exclude(category='').order_by('category', 'created_at', 'id'):
        name = slide.category.strip()
        if not name:
            continue
        category, _ = SlideCategory.objects.get_or_create(
            name=name,
            defaults={'position': len(category_positions)},
        )
        category_positions.setdefault(name, category.position)
        slide.category_ref_id = category.id
        slide.save(update_fields=['category_ref'])

    order_by_category = {}
    for slide in Slide.objects.order_by('category_ref_id', 'created_at', 'id'):
        key = slide.category_ref_id or 0
        position = order_by_category.get(key, 0)
        slide.sort_order = position
        slide.save(update_fields=['sort_order'])
        order_by_category[key] = position + 1


class Migration(migrations.Migration):

    dependencies = [
        ('slideapp', '0004_slide_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('position', 'name'),
            },
        ),
        migrations.AddField(
            model_name='slide',
            name='category_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slides', to='slideapp.slidecategory'),
        ),
        migrations.AddField(
            model_name='slide',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ('sort_order', '-updated_at', '-id')},
        ),
        migrations.RunPython(migrate_legacy_categories, migrations.RunPython.noop),
    ]
