# Generated by Django 6.0.5 on 2026-05-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideapp', '0005_slidecategory_slide_category_ref_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='content_hash',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='slide',
            name='html_cache',
            field=models.TextField(blank=True, default=''),
        ),
    ]
